stages:
- maven
- docker
- manifest

cache:
  untracked: true
  key: "ldap-m2"
  paths:
  - m2

build-jar:
  stage: maven
  image: harbor.rand0m.me/public/centos8-base:latest
  tags:
  - docker
  script:
  - sh scripts/build-maven.sh
  artifacts:
    paths:
    - ldap-app/target/ldap-app.jar
    expire_in: 20 mins

build-image-amd64:
  stage: docker
  image: docker
  only:
  - master
  tags:
  - docker
  script:
  - sh scripts/build-docker.sh