apiVersion: v1
kind: Secret
metadata:
   name: {{ .Release.Name }}-ldap-secrets
   annotations:
     "helm.sh/resource-policy": keep
type: Opaque
data:
   admin_password: "{{ .Values.ldap.admin_password | b64enc }}"
   mysql_root_password: {{ randAlphaNum 36 | b64enc | quote }}
   mysql_user_password: {{ randAlphaNum 36 | b64enc | quote }}
---
