{{- if .Values.ldap.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ldap-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - {{ .Values.ldap.hostname | quote }}
    secretName: {{ .Release.Name }}-ldap-tls
  rules:
  - host: {{ .Values.ldap.hostname | quote }}
    http:
      paths:
      - path: "/"
        pathType: "Prefix"
        backend:
          service:
            name: "{{ .Release.Name }}-ldap-service"
            port:
              number: 8080
{{- end }}
