version: "3"
services:
  mysql:
    image: mariadb
    restart: always
    volumes:
     - ${home}/data/mysql:/var/lib/mysql
    env_file:
     - ${home}/ldap-prod.env
  ldap:
    image: rmalchow/ldap
    restart: always
    volumes:
     - ${home}/data/ldap:/app/data
    env_file:
     - ${home}/ldap-prod.env
    ports:
    - 1389:389
    - 1080:8080
    