spring.mandatory-file-encoding: UTF-8
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
spring.http.encoding.force: true
spring.resources.cache.period: 1

spring.datasource.username: ${MYSQL_USER:ldap}
spring.datasource.password: ${MYSQL_PASSWORD:s3cr3t}
spring.datasource.url: jdbc:mariadb://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:ldap}



spring.mail.host: ${MAIL_HOST:127.0.0.1}
spring.mail.port: ${MAIL_PORT:25}
spring.mail.sender: ${MAIL_SENDER:me@example.com}
spring.mail.username: ${MAIL_USER:} 
spring.mail.password: ${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.starttls.enable: true

ldap.config.name: ${NAME:test ldap (local)}
ldap.config.url: ${URL:http://127.0.0.1:8080}
ldap.config.allowAnonymous: ${LDAP_ALLOW_ANONYMOUS:false}

flyway.enabled: true

apacheds:
   root: "${LDAP_DATA:/app/data}"
   adminPassword: "${LDAP_ADMIN_PW:s3cr3t}"
   partitions:
      - name: "main"
        dn: "${LDAP_ROOT_DN:dc=foo,dc=com}"
        organization: "${LDAP_ORG:bar}"
        units:
        - "people"
        - "groups"
   listeners:
      - type: plain
        port: ${LDAP_PORT:389}
ldap:
   xyz: "nase"
   registration:
      enabled: true