spring.mandatory-file-encoding: UTF-8
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
spring.http.encoding.force: true
spring.resources.cache.period: 1

spring:
   datasource:
      username: ${MYSQL_USER:ldap}
      password: ${MYSQL_PASSWORD:s3cr3t}
      url: jdbc:mariadb://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:ldap}
   reader:
      enabled: false
      username: ${MYSQL_USER:ldap}
      password: ${MYSQL_PASSWORD:s3cr3t}
      url: jdbc:mariadb://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:ldap}
   mail:
      host: ${MAIL_HOST:127.0.0.1}
      port: ${MAIL_PORT:25}
      sender: ${MAIL_SENDER:me@example.com}
      username: ${MAIL_USER:} 
      password: ${MAIL_PASSWORD:}
      properties.mail.smtp.starttls.enable: ${MAIL_STARTTLS:true}
ldap:
   config:
      name: ${NAME:test ldap (local)}
      url: ${URL:http://127.0.0.1:8080}
      allowAnonymous: ${LDAP_ALLOW_ANONYMOUS:false}
   registration:
      enabled: true
flyway.enabled: true

apacheds:
   root: "${LDAP_DATA:/app/data}"
   adminPassword: "${LDAP_ADMIN_PW:s3cr3t}"
   partitions:
      - name: "main"
        dn: "${LDAP_ROOT_DN:dc=foo,dc=com}"
        organization: "${LDAP_ORG:bar}"
        units:
        - "people"
        - "groups"
   listeners:
      - type: plain
        port: ${LDAP_PORT:389}
logging.level.org.apache: FATAL