version: "2"
networks:
  default:
    external:
      name: "ldap"
services:
  ldap:
    image: rmalchow/ldap
    restart: always
    volumes:
     - ldap-data:/app/data
    env_file:
     - ./ldap.env
    depends_on:
      - ldap-mysql
    ports:
    - 389:389
    - 8080:8080
    mem_limit: 384m
  ldap-mysql:
    image: mariadb:latest
    restart: always
    mem_limit: 128m
    volumes:
     - mysql-data:/var/lib/mysql
    env_file:
     - ./ldap.env
volumes:
  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /path/to/mysql-data
  ldap-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /path/to/ldap-data
