FROM harbor.rand0m.me/public/springboot:latest-alpine
MAINTAINER Ruben Malchow <ruben.malchow@gmail.com>
COPY ldap-app/target/ldap-app.jar ldap-app.jar
COPY ldap-app/config/application* /app/
#COPY scripts/app.sh ldap-app.sh
#CMD [ "/bin/bash", "ldap-app.sh" ]
